Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: dynamodbAccessRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
  InitFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: >
          const AWS = require("aws-sdk");
          const response = require('./cfn-response');
          const docClient = new AWS.DynamoDB.DocumentClient();
          exports.handler = function(event, context) {
            console.log(JSON.stringify(event,null,2));
            var params = {
              RequestItems: {
                "DynamoDBQuery-EventAnnouncements": [
                  {
                    PutRequest: {
                      Item: {
                        eventId: "98375E9D-7D3E-4DBF-A5AC-C7800B608F8E",
                        timePublished: "2020-04-01T20:38:25.213-07:00[America/Los_Angeles]",
                        subject: "Dog Hikers walk announcement",
                        content: "Next walk with the Dog Hikers! Discovery Park. No cats this time, Norman!"
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        eventId: "DA9B6265-18D9-43CB-874C-567A05DC1F01",
                        timePublished: "2020-03-11T12:36:11.643-07:00[America/Los_Angeles]",
                        subject: "Dinner Club",
                        content: "Dino's Pizza in Capitol Hill. First round of drinks are on June. Please RSVP by Wednesday."
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        eventId: "C7800B60-874C-18D9-4DBF-DA9B567A1E9D",
                        timePublished: "2020-03-18T12:36:11.643-07:00[America/Los_Angeles]",
                        subject: "Dinner Club",
                        content: "Jai Thai in Capitol Hill. Please RSVP by Wednesday."
                      }
                    }
                  }
                ]
              }
            };
            docClient.batchWrite(params, function(err, data) {
              if (err) {
                response.send(event, context, "FAILED", {});
              } else {
                response.send(event, context, "SUCCESS", {});
              }
            });
          };
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , "Arn" ]
      # 2020-02-27: [bp] updated from nodejs10.x in case it matters
      Runtime: nodejs12.x
      Timeout: 60
  DynamoDBQueryEventAnnouncements:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "eventId"
          AttributeType: "S"
        - AttributeName: "timePublished"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "eventId"
          KeyType: "HASH"
        - AttributeName: "timePublished"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "DynamoDBQuery-EventAnnouncements"
  InitializeEventAnnouncementsTable:
    Type: Custom::InitFunction
    DependsOn: DynamoDBQueryEventAnnouncements
    Properties:
      ServiceToken:
        Fn::GetAtt: [ InitFunction , "Arn" ]
      DynamoTableName:
        Ref: DynamoDBQueryEventAnnouncements
