package com.frank.springboot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// This is the server for our App
//
// This was generated by Spring Initialzr
// DO NOT CHANGE

@SpringBootApplication  // Tells the server this is a Spring Boot application
public class Bd6FirstSpringBootProjectApplication {

	public static void main(String[] args) {
		SpringApplication.run(Bd6FirstSpringBootProjectApplication.class, args);
	}

}
