Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: dynamodbAccessRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
  InitFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: >
          const AWS = require("aws-sdk");
          const response = require('./cfn-response');
          const docClient = new AWS.DynamoDB.DocumentClient();
          exports.handler = function(event, context) {
            console.log(JSON.stringify(event,null,2));
            var params = {
              RequestItems: {
                "Metrics-Reservations": [
                  {
                    PutRequest: {
                      Item: {
                        reservationId: "98375E9D-7D3E-4DBF-A5AC-C7800B608F8E",
                        guestId: "1",
                        checkInDate: "2020-03-08T03:00:00UTC",
                        numberOfNights: "1",
                        isCanceled: "false",
                        costPerNight: "125.0",
                        totalCost: "156.5"
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        reservationId: "DA9B6265-18D9-43CB-874C-567A05DC1F01",
                        guestId: "2",
                        checkInDate: "2020-03-08T03:00:00UTC",
                        numberOfNights: "3",
                        isCanceled: "false",
                        costPerNight: "100.0",
                        totalCost: "354.5"
                      }
                    }
                  }
                ]
              }
            };
            docClient.batchWrite(params, function(err, data) {
              if (err) {
                response.send(event, context, "FAILED", {});
              } else {
                response.send(event, context, "SUCCESS", {});
              }
            });
          };
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , "Arn" ]
      # 2020-02-27: [bp] updated from nodejs10.x in case it matters
      Runtime: nodejs12.x
      Timeout: 60
  Unit4MetricsReservations:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions" : [
      {
        "AttributeName" : "reservationId",
        "AttributeType" : "S"
      }
      ]
      "KeySchema" : [
      {
        "AttributeName" : "reservationId",
        "KeyType" : "HASH"
      }
      ]
      BillingMode: PAY_PER_REQUEST
      TableName: "Metrics-Reservations"
  InitializeEventsTable:
    Type: Custom::InitFunction
    DependsOn: Unit4MetricsReservations
    Properties:
      ServiceToken:
        Fn::GetAtt: [ InitFunction , "Arn" ]
      DynamoTableName:
        Ref: Unit4MetricsReservations
